pipeline {
  agent any

enviroment{
  githubURL = 'git@github.com',
  BRANCH = 'develop'
}
  stages {
    stage('checkout') {
      gitrepo = '${githubURL}'
    }
     stage('Login AWS') {
      steps {
        set +x
          sh "aws configure set aws_access_key_id $AWSKEY"
      }
    }    
    stage("Build") {
      steps {
        script{
          echo "Building the application..."
          sh "mvn clean install"
        }
      }
    }

    stage('Test') {
      step {
        script {
          sh 'pytest tests'
        }
      }
    }
   
    
    stage('Deploy') {
        steps {
          script {
            sh 'scp target/app.jar user@server:/opt/app/'
          }
      }
    }
    }
  post {
   steps {
     echo 'build success'
   }
  }
}
