pipeline {
  agent any
environment {
    AWS_ACCESS_KEY_ID     = credentials('aws-secret-key-id')
    AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')
}
  stages {
    stage("Build") {
      steps {
        echo "Building the application..."
        sh "mvn clean install"
      }
    }

    stage('Test') {
      steps {
        sh 'pytest tests'
      }
    }

    stage('Deploy') {
      steps {
        sh 'scp target/app.jar user@server:/opt/app/'
      }
    }
    stage('Login AWS') {
      steps {
          sh "aws configure set aws_access_key_id $AWSKEY"  # secrets should be passed via the credentials and read through env variables
      }
    }	
  }
}

